### PR TITLE
[Merged by Bors] - Fix Rust 1.63.0 clippy warnings

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist

- [x] Code contains useful comments
- [x] CRD change approved (or not applicable)
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)
- [x] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by adwk67 — APPROVED** [review]
LGTM.

**Comment by sbernauer** [comment]
I would say this is fixing a linter check and not worth putting in (and even disturbing) the Changelog. What do you think?

**Comment by adwk67** [comment]
> I would say this is fixing a linter check and not worth putting in (and even disturbing) the Changelog. What do you think?

I would say it is a good idea to document any and all changes to rust code (although I'm inconsistent :) - I added a changelog entry for this very same linter check in spark-k8s yesterday, but forgot it for airflow)

**Comment by teozkr** [comment]
I'm inclined to agree with @sbernauer, this is an internal change that has no user-visible impact.

**Comment by adwk67** [comment]
> I'm inclined to agree with @sbernauer, this is an internal change that has no user-visible impact.

I'm fine with that (I was actually thinking more for us, for tracking changes: but, yes, for minor things like that, it may end up obfuscating the important stuff)

**Comment by sbernauer** [comment]
Alright thanks for your input!
I do understand that you're fine without a changelog, if not please reopen and we can add it later on

**Pull request closed without merging**
