### PR TITLE
[Merged by Bors] - Change secret name in the LDAP test

### PR DESCRIPTION
**Pull request by fhennig**
# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by fhennig** [comment]
I changed the name of the secret to differ from the secret class and started a test 

https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/superset-operator-it-custom/22/

**Comment by fhennig** [comment]
@sbernauer I'm testing this now. If that works Maybe we could merge it as well?

**Comment by sbernauer** [comment]
Could you please explain why you think Secret and SecretClass should be named differently? :)

**Comment by fhennig** [comment]
Hmm, I think you didn't like this way of thinking in other places as well. But it's to ensure that exactly what happened in Trino doesn't happen. It is a feature that the names _can_ differ, and so I also want to test this. The same reason I also wouldn't want to call my resource `superset` but something like `demo-superset` in a demo, so the user can see that the name doesn't need to match the product name (for example).

But in this case it's really about testing that the secret retrieval is done using k8ssearch and not by matching the name of the SecretClass.

**Review by sbernauer — APPROVED** [review]
> But it's to ensure that exactly what happened in Trino doesn't happen

got me ;)

**Comment by fhennig** [comment]
bors merge

**Pull request closed without merging**
