### PR TITLE
fix: Fixed various issues in the CRD structure

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

Part of https://github.com/stackabletech/issues/issues/469

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM!

**Comment by lfrancke** [comment]
Is this a CRD change? Breaking?

**Comment by maltesander** [comment]
Its breaking in terms of removing a bad default (empty string) which would not have worked anyways if left out since the pods would not be able to read from / mount a secret with an empty name...
@sbernauer and i decided this is basically non breaking in terms of functionality and crd adaptation (since leaving it out would not work) and skip this in the arch meeting.

**Comment by sbernauer** [comment]
Agreed!

**Comment by lfrancke** [comment]
I probably need to ask better questions.
What I'm wondering is if people will need to change their custom resources as a result of this.

**Comment by maltesander** [comment]
If you did not specify the optional value and used the bad default, the deployed pods will never start.
So i would assume everyone that is using it has a value set here.

**Pull request merged**
